version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'chore(deps)'
    ignore:
      - dependency-name: '@types/vscode'
    groups:
      all:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
